language: go
go:
  - "1.15.x"

env:
  - GO111MODULE=on GOFLAGS=-mod=readonly GOPROXY=https://proxy.golang.org

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
  - GO111MODULE=off go get -u github.com/mattn/goveralls # Use `go install` in Go1.16
  - go mod download

script:
  - golangci-lint run ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci -ignore=testutil/*,testutil/mocks/*

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always