language: go
go:
  - "1.13.x"
  - "1.x"

env:
  global:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci -ignore=testutil/*,testutil/mocks/*

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/kage/

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always